<a href="https://colab.research.google.com/github/LinaMariaCastro/curso-ia-para-economia/blob/main/clases/3_Analisis_y_visualizacion_datos/2_Combinacion_Exportacion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Inteligencia Artificial con Aplicaciones en Economía I**

- 👩‍🏫 **Profesora:** [Lina María Castro](https://www.linkedin.com/in/lina-maria-castro)  
- 📧 **Email:** [lmcastroco@gmail.com](mailto:lmcastroco@gmail.com)  
- 🎓 **Universidad:** Universidad Externado de Colombia - Facultad de Economía

# 🛢️**Métodos de combinación y exportación de datos**

**Objetivos de Aprendizaje:**

Al finalizar este notebook, serás capaz de:
1.  **Combinar múltiples datasets** de forma eficiente utilizando las funciones `concat` y `merge` de pandas.
2.  **Exportar tus DataFrames resultantes** a diversos formatos para su uso posterior.

---

## Importar librerías

In [1]:
import os
import numpy as np
import pandas as pd

## Mejorar visualización de los dataframes

In [2]:
# Que muestre todas las columnas
pd.options.display.max_columns = None
# En los dataframes, mostrar los float con dos decimales
pd.options.display.float_format = '{:,.2f}'.format

## Establecer la ruta de los datasets

In [3]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
path = '/content/drive/MyDrive/2026-i-curso-ia-para-economia/datasets'

In [5]:
# Para establecer el directorio de los archivos
os.chdir(path)

---

## Unir Datos con `pd.concat` y `pd.merge`

Rara vez un proyecto de análisis económico se basa en una sola fuente de datos, por tanto, es muy importante saber combinar datasets de manera lógica y correcta.

### Concatenación con `pd.concat()`

`concat` nos permite "apilar" DataFrames uno encima del otro (eje 0) o uno al lado del otro (eje 1). Su uso más común es para agregar nuevas filas al DataFrame.

**Ejemplo:** Eres un analista del DANE, de la Coordinación de Comercio Internacional, y tienes el archivo de las exportaciones de bienes de julio 2024. Al mes siguiente, recibes el archivo de agosto. `concat` es la acción de tomar las hojas del nuevo reporte y añadirlas al final del reporte del mes anterior. Esto se suele hacer con los archivos de enero a diciembre para construir un único archivo consolidado del año.

In [6]:
df_expo_jul = pd.read_excel('expo_bienes_2024/07_Exportaciones_2024_Julio.xlsx')
df_expo_jul.head(3)

,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO
0,202407,7,99,89,Aduanas de Cúcuta,2,"901,333,018.00",36,0,2,54001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,6027733007951,1,Inicial,89,CUC,54,NORTE DE SANTANDER,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,8212102000,54,NORTE DE SANTANDER,11,U,Unidades o artículos,74.00,"3,509.35","3,498.00","5,476.00","21,983,730.56",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739047723,20240729,C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18
1,202407,6,99,89,Aduanas de Cúcuta,2,"901,333,018.00",36,0,2,54001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,6027733007951,1,Inicial,89,CUC,54,NORTE DE SANTANDER,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3401300000,54,NORTE DE SANTANDER,33,KG,Kilogramo,515.00,516.67,515.00,780.00,"3,131,356.80",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739047723,20240729,C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18
2,202407,5,99,89,Aduanas de Cúcuta,2,"901,333,018.00",36,0,2,54001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,6027733007951,1,Inicial,89,CUC,54,NORTE DE SANTANDER,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3809910000,54,NORTE DE SANTANDER,33,KG,Kilogramo,"1,056.00","1,059.42","1,056.00","1,600.00","6,423,296.00",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739047723,20240729,C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18

In [7]:
df_expo_ago = pd.read_excel('expo_bienes_2024/08_Exportaciones_2024_Agosto.xlsx')
df_expo_ago.head(3)

,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO
0,202408,4,99,89,Aduanas de Cúcuta,2,"860,016,695.00",36,0,2,11001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),BARQUISIMETO,"6,027,732,667,512.00",1,Inicial,89,CUC,11,BOGOTA DC,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3405300000,11,BOGOTA DC,33,KG,Kilogramo,76.57,83.12,76.57,88.40,"358,651.17",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739046259,20240802,PHILAAC SAS,AC 24 95 12 BG 16,"860,066,749.00",AGENCIA DE ADUANAS ADUANAMIENTOS LTDA NI...,DISPINZAGO CA,AV LAS INDUSTRIAS ENTRE CLL EN PROYECTO Y CLL ...
1,202408,2,99,89,Aduanas de Cúcuta,2,"860,016,695.00",36,0,2,11001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),BARQUISIMETO,"6,027,732,667,512.00",1,Inicial,89,CUC,11,BOGOTA DC,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3208900000,11,BOGOTA DC,33,KG,Kilogramo,"4,578.92","4,970.90","4,578.92","10,773.70","43,710,409.21",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739046259,20240802,PHILAAC SAS,AC 24 95 12 BG 16,"860,066,749.00",AGENCIA DE ADUANAS ADUANAMIENTOS LTDA NI...,DISPINZAGO CA,AV LAS INDUSTRIAS ENTRE CLL EN PROYECTO Y CLL ...
2,202408,3,99,89,Aduanas de Cúcuta,2,"860,016,695.00",36,0,2,11001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),BARQUISIMETO,"6,027,732,667,512.00",1,Inicial,89,CUC,11,BOGOTA DC,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3208100000,11,BOGOTA DC,33,KG,Kilogramo,"3,859.15","4,189.52","3,859.15","5,291.02","21,466,408.88",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739046259,20240802,PHILAAC SAS,AC 24 95 12 BG 16,"860,066,749.00",AGENCIA DE ADUANAS ADUANAMIENTOS LTDA NI...,DISPINZAGO CA,AV LAS INDUSTRIAS ENTRE CLL EN PROYECTO Y CLL ...

In [8]:
df_expo_jul.shape

(5427, 72)

In [9]:
df_expo_ago.shape

(7557, 72)

In [10]:
# Para concatenar un dataframe debajo del otro (axis=0)
df_expo_2024 = pd.concat([df_expo_jul, df_expo_ago], axis = 0, ignore_index=True)
df_expo_2024.head(3)

,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO
0,202407,7,99,89,Aduanas de Cúcuta,2,"901,333,018.00",36,0,2,54001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,"6,027,733,007,951.00",1,Inicial,89,CUC,54,NORTE DE SANTANDER,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,8212102000,54,NORTE DE SANTANDER,11,U,Unidades o artículos,74.00,"3,509.35","3,498.00","5,476.00","21,983,730.56",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739047723,20240729,C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18
1,202407,6,99,89,Aduanas de Cúcuta,2,"901,333,018.00",36,0,2,54001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,"6,027,733,007,951.00",1,Inicial,89,CUC,54,NORTE DE SANTANDER,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3401300000,54,NORTE DE SANTANDER,33,KG,Kilogramo,515.00,516.67,515.00,780.00,"3,131,356.80",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739047723,20240729,C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18
2,202407,5,99,89,Aduanas de Cúcuta,2,"901,333,018.00",36,0,2,54001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,"6,027,733,007,951.00",1,Inicial,89,CUC,54,NORTE DE SANTANDER,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3809910000,54,NORTE DE SANTANDER,33,KG,Kilogramo,"1,056.00","1,059.42","1,056.00","1,600.00","6,423,296.00",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739047723,20240729,C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18

In [11]:
df_expo_2024.tail(3)

,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO
12981,202408,1,99,39,Impuestos y Aduanas de Maicao,2,"900,797,309.00",36,0,2,13001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),CARACAS,"6,027,733,116,785.00",1,Inicial,39,MAI,13,BOLIVAR,0,0,0,0,NaN,USD,3,Terrestre (carretero),169,CO,COLOMBIA,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,6809110000,13,BOLIVAR,82,M2,Metro cuadrado,"30,657.36","30,793.61","30,657.36","11,744.12","47,728,456.00",0.00,0.00,0.00,0.00,39,Impuestos y Aduanas de Maicao,202408,6007739427431,20240823,KNAUF DISTRIBUIDORA S.A.S.,BRR BOSQUE TV 54 21 A 120 CENTRO EMPR...,"890,403,077.00",AGENCIA DE ADUANAS HUBEMAR S.A.S NIVEL 1,"RAPIDFIX COMERCIALIZADORA, C.A.",CALLE LOS ANGELES LC GALPON N35
12982,202408,1,99,39,Impuestos y Aduanas de Maicao,2,"901,541,071.00",36,0,2,8001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),CARACAS,"6,027,734,345,169.00",1,Inicial,39,MAI,13,BOLIVAR,0,0,0,0,NaN,USD,3,Terrestre (carretero),169,CO,COLOMBIA,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,6809110000,13,BOLIVAR,82,M2,Metro cuadrado,"40,246.34","267,228.00","261,384.00","85,612.64","345,063,457.77",0.00,0.00,0.00,0.00,39,Impuestos y Aduanas de Maicao,202408,6007740519871,20240824,COMERCIALIZADORA INTERNACIONAL PROARCA S.A.S,CR 53 106 280 OF 8 A P 8 TO B CENTRO EMPR...,"800,227,414.00",AGENCIA DE ADUANAS MERCO S.A.S NIVEL 1,PRODUCTOS ARQUITECTONICOS PROARCA C. A.,AV. MILAN CON CALLE BOSTON LOCAL PARCELA 1028 ...
12983,202408,1,99,39,Impuestos y Aduanas de Maicao,2,"830,070,950.00",36,0,2,5001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MATURIN,"6,027,733,628,765.00",1,Inicial,39,MAI,13,BOLIVAR,0,0,0,0,NaN,USD,3,Terrestre (carretero),169,CO,COLOMBIA,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,2909430000,13,BOLIVAR,33,KG,Kilogramo,"29,760.00","29,760.00","29,760.00","52,587.38","210,947,438.51",0.00,"4,849.42",0.00,0.00,39,Impuestos y Aduanas de Maicao,202408,6007740250561,20240821,C I CONALEX SAS,CR 43 A 1 A SUR 69 IN 703,"811,001,259.00",AGENCIA DE ADUANAS ROLDAN S.A.S NIVEL 1,"PETRO SERVICES GSM, C.A",AV MONTERREY CC SERVIMAS MONTERREY NIVEL 1

In [12]:
df_expo_2024.shape

(12984, 72)

In [13]:
# Para concatenar un dataframe al lado del otro, se coloca axis = 1
df_expo_2024_hor = pd.concat([df_expo_jul, df_expo_ago], axis = 1)
df_expo_2024_hor.head(3)

,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO
0,"202,407.00",7.00,99.00,89.00,Aduanas de Cúcuta,2.00,"901,333,018.00",36.00,0.00,2.00,"54,001.00",850.00,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,"6,027,733,007,951.00",1.00,Inicial,89.00,CUC,54.00,NORTE DE SANTANDER,0.00,0.00,0.00,0.00,NaN,USD,3.00,Terrestre (carretero),13.00,AF,AFGANISTÁN,1.00,198.00,Exportación definitiva de mercancías de fabric...,1.00,1.00,Unico,1.00,Definitivos al embarque,8.00,NO,N,NO,"8,212,102,000.00",54.00,NORTE DE SANTANDER,11.00,U,Unidades o artículos,74.00,"3,509.35","3,498.00","5,476.00","21,983,730.56",0.00,0.00,0.00,0.00,89.00,Aduanas de Cúcuta,"202,407.00","6,007,739,047,723.00","20,240,729.00",C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18,202408,4,99,89,Aduanas de Cúcuta,2,"860,016,695.00",36,0,2,11001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),BARQUISIMETO,"6,027,732,667,512.00",1,Inicial,89,CUC,11,BOGOTA DC,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3405300000,11,BOGOTA DC,33,KG,Kilogramo,76.57,83.12,76.57,88.40,"358,651.17",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739046259,20240802,PHILAAC SAS,AC 24 95 12 BG 16,"860,066,749.00",AGENCIA DE ADUANAS ADUANAMIENTOS LTDA NI...,DISPINZAGO CA,AV LAS INDUSTRIAS ENTRE CLL EN PROYECTO Y CLL ...
1,"202,407.00",6.00,99.00,89.00,Aduanas de Cúcuta,2.00,"901,333,018.00",36.00,0.00,2.00,"54,001.00",850.00,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,"6,027,733,007,951.00",1.00,Inicial,89.00,CUC,54.00,NORTE DE SANTANDER,0.00,0.00,0.00,0.00,NaN,USD,3.00,Terrestre (carretero),13.00,AF,AFGANISTÁN,1.00,198.00,Exportación definitiva de mercancías de fabric...,1.00,1.00,Unico,1.00,Definitivos al embarque,8.00,NO,N,NO,"3,401,300,000.00",54.00,NORTE DE SANTANDER,33.00,KG,Kilogramo,515.00,516.67,515.00,780.00,"3,131,356.80",0.00,0.00,0.00,0.00,89.00,Aduanas de Cúcuta,"202,407.00","6,007,739,047,723.00","20,240,729.00",C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18,202408,2,99,89,Aduanas de Cúcuta,2,"860,016,695.00",36,0,2,11001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),BARQUISIMETO,"6,027,732,667,512.00",1,Inicial,89,CUC,11,BOGOTA DC,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3208900000,11,BOGOTA DC,33,KG,Kilogramo,"4,578.92","4,970.90","4,578.92","10,773.70","43,710,409.21",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739046259,20240802,PHILAAC SAS,AC 24 95 12 BG 16,"860,066,749.00",AGENCIA DE ADUANAS ADUANAMIENTOS LTDA NI...,DISPINZAGO CA,AV LAS INDUSTRIAS ENTRE CLL EN PROYECTO Y CLL ...
2,"202,407.00",5.00,99.00,89.00,Aduanas de Cúcuta,2.00,"901,333,018.00",36.00,0.00,2.00,"54,001.00",850.00,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MERIDA,"6,027,733,007,951.00",1.00,Inicial,89.00,CUC,54.00,NORTE DE SANTANDER,0.00,0.00,0.00,0.00,NaN,USD,3.00,Terrestre (carretero),13.00,AF,AFGANISTÁN,1.00,198.00,Exportación definitiva de mercancías de fabric...,1.00,1.00,Unico,1.00,Definitivos al embarque,8.00,NO,N,NO,"3,809,910,000.00",54.00,NORTE DE SANTANDER,33.00,KG,Kilogramo,"1,056.00","1,059.42","1,056.00","1,600.00","6,423,296.00",0.00,0.00,0.00,0.00,89.00,Aduanas de Cúcuta,"202,407.00","6,007,739,047,723.00","20,240,729.00",C.I. FERGUTECH SAS,BG E 2 3 ZN FRANCA,"901,557,278.00",BERZATEX SAS.,COMERCIALIZADORA Y DISTRIBUIDORA LA CHINA C.A,AV BOLIVAR LC NO S/N ZONA ENTRE AV 16 Y 18,202408,3,99,89,Aduanas de Cúcuta,2,"860,016,695.00",36,0,2,11001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),BARQUISIMETO,"6,027,732,667,512.00",1,Inicial,89,CUC,11,BOGOTA DC,0,0,0,0,NaN,USD,3,Terrestre (carretero),13,AF,AFGANISTÁN,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,3208100000,11,BOGOTA DC,33,KG,Kilogramo,"3,859.15","4,189.52","3,859.15","5,291.02","21,466,408.88",0.00,0.00,0.00,0.00,89,Aduanas de Cúcuta,202407,6007739046259,20240802,PHILAAC SAS,AC 24 95 12 BG 16,"860,066,749.00",AGENCIA DE ADUANAS ADUANAMIENTOS LTDA NI...,DISPINZAGO CA,AV LAS INDUSTRIAS ENTRE CLL EN PROYECTO Y CLL ...

In [14]:
df_expo_2024_hor.shape

(7557, 144)

In [15]:
df_expo_2024_hor.tail(3)

,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO,FECHA_PROCESO,NUMERO_SERIE,OFICINA,COD_ADUANA_DESPACHO,ADUANA_DESPACHO,TIPO_IDENT,NIT_EXPORTADOR,TIPO_USUARIO,COD_USUARIO,CLASE_EXPORTADOR,COD_DPTO_EXPORTADOR,COD_PAIS_DESTINO_NUM,COD_PAIS_DESTINO_ALF,COD_PAIS_DESTINO,PAIS_DESTINO_FINAL,CIUDAD_DESTINATARIO,NUM_SOLICITUD_AUTO_EMBARQUE,TIPO_DECLARACION,TIPO_DESPACHO,COD_LUGAR_SALIDA_NUM,COD_LUG_SALIDA_ALF,COD_REGION_PROCEDENCIA,REGION_PROCEDENCIA,NUM__DECLA_EXPORTACION_ANT,FECH_DECLA_EXPORTACION_ANT,NUM_DECLARACION_PRECEDENTE,FECH_DECLA_PRECEDENTE,COD_MODALIDAD_PRECEDENTE,COD_MONEDA_TRANSACCION,COD_MODO_TRANSPORTE,MODO_TRANSPORTE,BANDERA,COD_NACIONALIDAD_BANDERA,NACIONALIDAD_BANDERA,COD_REGIMEN_CAN,COD_MODALIDAD_EXPORTACION,MODALIDAD_EXPORTACION,FORMA_PAGO,COD_TIPO_EMBARQUE,TIPO_DE_EMBARQUE,COD_TIPO_DATOS,TIPO_DE_DATOS,TIPO_CERTIFICADO_ORIGEN,SISTEMAS_ESPECIALES,COD_EXPORTACION_TRANSITO,EXPORTACION_EN_TRANSITO,SUBPARTIDA,COD_REGION_ORIGEN,REGION_DE_ORIGEN,COD_UNIDAD_FISICA_NUM,COD_UNIDAD_FISICA_ALF,UNIDAD_FISICA,CANTIDAD_UNIDADES_FISICAS,PESO_BRUTO_KGS,PESO_NETO_KGS,VALOR_FOB_USD,VALOR_FOB_PESOS,VLR_SERIE_AGREGADO_NAL_USD,VALOR_SERIE_FLETES_USD,VALOR_SERIE_SEGUROS_USD,VLR_SERIE_OTROS_GASTOS_USD,COD_ADUANA_SALIDA,ADUANA_SALIDA,FECHA_SOLICITUD_AUTO_EMBARQUE,NUMERO_FORMULARIO,FECHA_DECLARACION_EXPORTACION,RAZON_SOCIAL_EXPORTADOR,DIREC_EXPORTADOR,NIT_DECLARANTE,RAZON_SOCIAL_DECLARANTE,RAZON_SOCIAL_DESTINATARIO,DOMICILIO_DESTINATARIO
7554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202408,1,99,39,Impuestos y Aduanas de Maicao,2,"900,797,309.00",36,0,2,13001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),CARACAS,"6,027,733,116,785.00",1,Inicial,39,MAI,13,BOLIVAR,0,0,0,0,NaN,USD,3,Terrestre (carretero),169,CO,COLOMBIA,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,6809110000,13,BOLIVAR,82,M2,Metro cuadrado,"30,657.36","30,793.61","30,657.36","11,744.12","47,728,456.00",0.00,0.00,0.00,0.00,39,Impuestos y Aduanas de Maicao,202408,6007739427431,20240823,KNAUF DISTRIBUIDORA S.A.S.,BRR BOSQUE TV 54 21 A 120 CENTRO EMPR...,"890,403,077.00",AGENCIA DE ADUANAS HUBEMAR S.A.S NIVEL 1,"RAPIDFIX COMERCIALIZADORA, C.A.",CALLE LOS ANGELES LC GALPON N35
7555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202408,1,99,39,Impuestos y Aduanas de Maicao,2,"901,541,071.00",36,0,2,8001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),CARACAS,"6,027,734,345,169.00",1,Inicial,39,MAI,13,BOLIVAR,0,0,0,0,NaN,USD,3,Terrestre (carretero),169,CO,COLOMBIA,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,6809110000,13,BOLIVAR,82,M2,Metro cuadrado,"40,246.34","267,228.00","261,384.00","85,612.64","345,063,457.77",0.00,0.00,0.00,0.00,39,Impuestos y Aduanas de Maicao,202408,6007740519871,20240824,COMERCIALIZADORA INTERNACIONAL PROARCA S.A.S,CR 53 106 280 OF 8 A P 8 TO B CENTRO EMPR...,"800,227,414.00",AGENCIA DE ADUANAS MERCO S.A.S NIVEL 1,PRODUCTOS ARQUITECTONICOS PROARCA C. A.,AV. MILAN CON CALLE BOSTON LOCAL PARCELA 1028 ...
7556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202408,1,99,39,Impuestos y Aduanas de Maicao,2,"830,070,950.00",36,0,2,5001,850,VEN,VE,VENEZUELA (REPÚBLICA BOLIVARIANA DE),MATURIN,"6,027,733,628,765.00",1,Inicial,39,MAI,13,BOLIVAR,0,0,0,0,NaN,USD,3,Terrestre (carretero),169,CO,COLOMBIA,1,198,Exportación definitiva de mercancías de fabric...,1,1,Unico,1,Definitivos al embarque,8,NO,N,NO,2909430000,13,BOLIVAR,33,KG,Kilogramo,"29,760.00","29,760.00","29,760.00","52,587.38","210,947,438.51",0.00,"4,849.42",0.00,0.00,39,Impuestos y Aduanas de Maicao,202408,6007740250561,20240821,C I CONALEX SAS,CR 43 A 1 A SUR 69 IN 703,"811,001,259.00",AGENCIA DE ADUANAS ROLDAN S.A.S NIVEL 1,"PETRO SERVICES GSM, C.A",AV MONTERREY CC SERVIMAS MONTERREY NIVEL 1

### Cruce de Información con `pd.merge()`

`merge` es una de las operaciones más poderosas. Emula los `JOIN` de SQL y nos permite combinar DataFrames basándose en el valor de una o más columnas en común (llaves o "keys").

**Ejemplo:** El Banco de la República te contrata. Te entregan una tabla con el Indicador de Seguimiento a la Economía (ISE) para cada mes. Por otro lado, la Bolsa de Valores de Colombia te da una tabla con el volumen de negociación del índice COLCAP, también para cada mes. `merge` es la operación de tomar estas dos tablas y, usando la columna "mes" como el punto de conexión, crear una nueva tabla más rica que contenga tanto el ISE como el volumen del COLCAP en la misma fila para cada mes.

Vamos a explorar los 4 tipos de `merge` más comunes: `inner`, `left`, `right`, y `outer`.

![Tipos de merge](https://drive.google.com/uc?id=1JQ_QH90nibxiBXoZezP4GgtMFNMp7gzV)

In [16]:
# Para el ejemplo, vamos a crear dos dataframes

# DataFrame 1: Datos de población por país
df_poblacion = pd.DataFrame({
    'codigo_pais': ['COL', 'MEX', 'PER', 'ECU'],
    'poblacion_millones': [52.1, 128.9, 34.0, 18.0]
})

# DataFrame 2: Datos de Llegada de Inversión Extranjera Directa (IED)
# Nota: No tenemos datos para Ecuador (ECU), pero sí para Argentina (ARG), que no está en el otro DF.
df_ied = pd.DataFrame({
    'iso_code': ['COL', 'MEX', 'PER', 'ARG'],
    'ied_millones_usd': [17048, 35292, 11738, 15055]
})

print("Población:")
display(df_poblacion)
print("IED:")
display(df_ied)

Población:

  codigo_pais  poblacion_millones
0         COL               52.10
1         MEX              128.90
2         PER               34.00
3         ECU               18.00

IED:

  iso_code  ied_millones_usd
0      COL             17048
1      MEX             35292
2      PER             11738
3      ARG             15055

#### MERGE TIPO 1: INNER JOIN (Intersección)

Solo nos devuelve las filas donde la llave ('codigo_pais'/'iso_code') existe en AMBOS DataFrames.

In [17]:
df_inner = pd.merge(df_poblacion, df_ied, left_on='codigo_pais', right_on='iso_code', how='inner')

print("\n--- INNER JOIN ---")
print("Resultado: Solo países presentes en ambos datasets.")
display(df_inner)

--- INNER JOIN ---
Resultado: Solo países presentes en ambos datasets.

  codigo_pais  poblacion_millones iso_code  ied_millones_usd
0         COL               52.10      COL             17048
1         MEX              128.90      MEX             35292
2         PER               34.00      PER             11738

#### MERGE TIPO 2: LEFT JOIN

Mantiene TODAS las filas del DataFrame de la izquierda ('df_poblacion') y trae los datos del de la derecha si la llave coincide. Si no, pone NaN.

In [18]:
df_left = pd.merge(df_poblacion, df_ied, left_on='codigo_pais', right_on='iso_code', how='left')

print("\n--- LEFT JOIN ---")
print("Resultado: Todos los países de 'población', con datos de IED si están disponibles.")
display(df_left)

--- LEFT JOIN ---
Resultado: Todos los países de 'población', con datos de IED si están disponibles.

  codigo_pais  poblacion_millones iso_code  ied_millones_usd
0         COL               52.10      COL         17,048.00
1         MEX              128.90      MEX         35,292.00
2         PER               34.00      PER         11,738.00
3         ECU               18.00      NaN               NaN

#### MERGE TIPO 3: RIGHT JOIN
Mantiene TODAS las filas del DataFrame de la derecha ('df_ied') y trae los datos del de la izquierda si la llave coincide.

In [19]:
df_right = pd.merge(df_poblacion, df_ied, left_on='codigo_pais', right_on='iso_code', how='right')

print("\n--- RIGHT JOIN ---")
print("Resultado: Todos los países de 'IED', con datos de población si están disponibles.")
display(df_right)

--- RIGHT JOIN ---
Resultado: Todos los países de 'IED', con datos de población si están disponibles.

  codigo_pais  poblacion_millones iso_code  ied_millones_usd
0         COL               52.10      COL             17048
1         MEX              128.90      MEX             35292
2         PER               34.00      PER             11738
3         NaN                 NaN      ARG             15055

#### MERGE TIPO 4: OUTER JOIN (Unión Completa)

Mantiene TODAS las filas de AMBOS DataFrames. Rellena con NaN donde no hay correspondencia.

In [20]:
df_outer = pd.merge(df_poblacion, df_ied, left_on='codigo_pais', right_on='iso_code', how='outer')

print("\n--- OUTER JOIN ---")
print("Resultado: Todos los países de ambos datasets.")
display(df_outer)

--- OUTER JOIN ---
Resultado: Todos los países de ambos datasets.

  codigo_pais  poblacion_millones iso_code  ied_millones_usd
0         NaN                 NaN      ARG         15,055.00
1         COL               52.10      COL         17,048.00
2         ECU               18.00      NaN               NaN
3         MEX              128.90      MEX         35,292.00
4         PER               34.00      PER         11,738.00

#### Ejercicios

1. Tienes el siguiente dataframe `df_econ` con datos económicos para Colombia, México, Perú y Brasil y el dataframe `df_poblacion` que creamos previamente. Usando un `merge`, crea un nuevo DataFrame llamado `df_final` que contenga el PIB per cápita, la inflación, las exportaciones y la población para cada país. ¿Qué tipo de `join` es el más apropiado si quieres mantener todos los datos de `df_econ`?

In [21]:
# Datos económicos por país
df_econ = pd.DataFrame({
    'pais_iso': ['COL', 'MEX', 'PER', 'BRA'],
    'PIB_per_capita': [7917, 13954, 8316, 10296],
    'Inflacion': [6.61, 4.72, 2.01, 4.83],
    'Exportaciones': [49600, 680790, 74700, 337000]
})
df_econ

  pais_iso  PIB_per_capita  Inflacion  Exportaciones
0      COL            7917       6.61          49600
1      MEX           13954       4.72         680790
2      PER            8316       2.01          74700
3      BRA           10296       4.83         337000

In [22]:
# Respuesta:
df_final = pd.merge(df_econ, df_poblacion, left_on='pais_iso', right_on='codigo_pais', how='left')
print("DataFrame Final:")
display(df_final)

DataFrame Final:

,pais_iso,PIB_per_capita,Inflacion,Exportaciones,codigo_pais,poblacion_millones
0,COL,7917,6.61,49600,COL,52.10
1,MEX,13954,4.72,680790,MEX,128.90
2,PER,8316,2.01,74700,PER,34.00
3,BRA,10296,4.83,337000,NaN,NaN

In [23]:
# La columna codigo_pais sobra, por lo que la vamos a borrar
df_final.drop(columns=['codigo_pais'], inplace=True)
df_final

  pais_iso  PIB_per_capita  Inflacion  Exportaciones  poblacion_millones
0      COL            7917       6.61          49600               52.10
1      MEX           13954       4.72         680790              128.90
2      PER            8316       2.01          74700               34.00
3      BRA           10296       4.83         337000                 NaN

2. Tenemos estas dos tablas, una con países y su PIB, y otra con países y su índice de desarrollo humano (IDH). No todos los países están en ambas tablas. Discutan con su compañero qué tabla resultante obtendrían con un inner join vs un outer join.

In [24]:
# DataFrame 1: Datos de PIB por país
df_pib = pd.DataFrame({
    'pais': ['BRA', 'ARG', 'PER', 'CHL'],
    'pib_millones_usd': [2188, 604, 283, 329]
})

# DataFrame 2: Datos IDH por país
df_idh = pd.DataFrame({
    'pais': ['BRA', 'CHL', 'COL', 'PER', 'MEX'],
    'IDH': [0.786, 0.878, 0.788, 0.794, 0.789],
    'Categoría': ['Alto', 'Muy alto', 'Alto', 'Alto', 'Alto']
})

print("PIB:")
display(df_pib)
print("IDH:")
display(df_idh)

PIB:

  pais  pib_millones_usd
0  BRA              2188
1  ARG               604
2  PER               283
3  CHL               329

IDH:

  pais  IDH Categoría
0  BRA 0.79      Alto
1  CHL 0.88  Muy alto
2  COL 0.79      Alto
3  PER 0.79      Alto
4  MEX 0.79      Alto

In [25]:
df_inner = pd.merge(df_pib, df_idh, on='pais', how='inner')
df_inner

  pais  pib_millones_usd  IDH Categoría
0  BRA              2188 0.79      Alto
1  PER               283 0.79      Alto
2  CHL               329 0.88  Muy alto

In [26]:
df_outer = pd.merge(df_pib, df_idh, on='pais', how='outer')
df_outer

  pais  pib_millones_usd  IDH Categoría
0  ARG            604.00  NaN       NaN
1  BRA          2,188.00 0.79      Alto
2  CHL            329.00 0.88  Muy alto
3  COL               NaN 0.79      Alto
4  MEX               NaN 0.79      Alto
5  PER            283.00 0.79      Alto

3.  He intentado hacer un merge entre estos dos DataFrames, pero Python me da un error. ¿Quién puede ver por qué está fallando el código?

In [27]:
# DataFrame 1: Datos de PIB per cápita por país
df_pib_pc = pd.DataFrame({
    'país_iso': ['COL', 'MEX', 'PER', 'BRA'],
    'PIB_per_capita': [7917, 13954, 8316, 10296]
})

# DataFrame 2: Datos de inflación por país
df_inflacion = pd.DataFrame({
    'pais_iso': ['COL', 'MEX', 'PER', 'BRA'],
    'Inflacion': [6.61, 4.72, 2.01, 4.83]
})

print("PIB per cápita:")
display(df_pib_pc)
print("Inflación:")
display(df_inflacion)

PIB per cápita:

  país_iso  PIB_per_capita
0      COL            7917
1      MEX           13954
2      PER            8316
3      BRA           10296

Inflación:

  pais_iso  Inflacion
0      COL       6.61
1      MEX       4.72
2      PER       2.01
3      BRA       4.83

In [28]:
df_merge = pd.merge(df_pib_pc, df_inflacion, on='pais_iso', how='inner')
df_merge

KeyError: 'pais_iso'

In [29]:
# Solución
df_merge = pd.merge(df_pib_pc, df_inflacion, left_on='país_iso', right_on='pais_iso', how='inner')
df_merge

  país_iso  PIB_per_capita pais_iso  Inflacion
0      COL            7917      COL       6.61
1      MEX           13954      MEX       4.72
2      PER            8316      PER       2.01
3      BRA           10296      BRA       4.83

4. Y en este merge, ¿qué está fallando?

In [30]:
# DataFrame 1: Datos de PIB en USD por municipio
df_pib_usd = pd.DataFrame({
    'cod_municipio': ['85424', '16784', '13968', '15978'],
    'PIB_usd': [417, 1848, 283, 2188]
})

# DataFrame 2: Datos de poblacion por municipio
df_poblacion = pd.DataFrame({
    'cod_municipio': [85424, 16784, 13968, 15978],
    'Población': ['49600', '680790', '74700', '337000']
})

print("PIB en USD:")
display(df_pib_usd)
print("Población:")
display(df_poblacion)

PIB en USD:

  cod_municipio  PIB_usd
0         85424      417
1         16784     1848
2         13968      283
3         15978     2188

Población:

   cod_municipio Población
0          85424     49600
1          16784    680790
2          13968     74700
3          15978    337000

In [31]:
df_combinado = pd.merge(df_pib_usd, df_poblacion, on='cod_municipio', how='inner')
df_combinado

ValueError: You are trying to merge on object and int64 columns for key 'cod_municipio'. If you wish to proceed you should use pd.concat

In [32]:
# Solución
df_poblacion['cod_municipio'] = df_poblacion['cod_municipio'].astype(str)
df_combinado = pd.merge(df_pib_usd, df_poblacion, on='cod_municipio', how='inner')
df_combinado

  cod_municipio  PIB_usd Población
0         85424      417     49600
1         16784     1848    680790
2         13968      283     74700
3         15978     2188    337000

#### Pregunta de discusión

¿Qué harían si al intentar unir dos tablas del gobierno por "nombre del municipio", descubren que "Bogotá D.C." en una tabla se llama "Bogota" y en la otra se llama Bogotá? ¿Cómo afecta esto a los diferentes tipos de join?

#### Ejemplos aplicados a Economía

- **Scoring de Crédito:** Unir el historial de crédito de un cliente (desde una base de datos SQL) con sus datos de redes sociales (desde una API que devuelve JSON) para crear un perfil de riesgo más completo.

- **Análisis de Política Pública:** Combinar datos de ejecución presupuestal de municipios (archivo CSV del gobierno) con indicadores de pobreza del DANE (tabla en Excel) con el fin de evaluar el impacto del gasto.

- **Investigación Macroeconómica:** Fusionar series de tiempo 2000-2025 sobre la inflación y el desempleo de todos los países de Latam (varios archivos de Excel) con el fin de crear un panel de datos y analizar el comportamiento de estas dos variables en el tiempo.

---

## Guardar / exportar datos

Una vez que hemos limpiado, combinado y analizado nuestros datos, el último paso es guardarlos. Esto nos permite compartir resultados o usarlos en otros programas (como R, Stata, o Tableau).

### Guardar en CSV (Comma-Separated Values) - el más común

In [33]:
df_combinado.to_csv('Descargas/Datos_municipio.csv', encoding ='utf-8', index = False)

### Guardar en TXT

In [34]:
df_combinado.to_csv('Descargas/Datos_municipio.txt', sep="|", decimal=',', encoding ='utf-8', index= False)

### Guardar en JSON

El formato 'records' es muy útil para la web y APIs. Significa que cada fila del DataFrame se convertirá en un diccionario (JSON object) dentro de una lista.

indent=4: Agrega sangría de 4 espacios en el JSON para que sea más legible.
Si no se coloca, todo el JSON queda en una sola línea.

In [35]:
df_final.to_json('Descargas/datos_macro_final.json', orient='records', indent=4)

### Guardar en Excel

In [36]:
df_combinado.to_excel("Descargas/Datos_municipio.xlsx", index=False)

#### Guardar más de un dataframe en Excel

In [37]:
with pd.ExcelWriter('Descargas/Ejemplo.xlsx') as writer:
    df_combinado.to_excel(writer, sheet_name='Municipio', index=False)
    df_final.to_excel(writer, sheet_name='Macro', index=False)

#### Guardar un dataframe en un Excel que ya existe como una hoja adicional (mode='a)

Si la hoja ya existe, la reemplaza.

In [38]:
with pd.ExcelWriter('Descargas/Ejemplo.xlsx', mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    df_expo_2024.to_excel(writer, sheet_name='Expo', index = False)